#!/usr/bin/env php
<?php
    require('vendor/autoload.php');
    if(file_exists('mvc.conf.php')) require('mvc.conf.php');
    $console = new Pico\Console\Console();
    $status = $console->run();
    exit($status);
